//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanCNPM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoanCNPM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baga_inox_10_ly_mau_titan_cho_exciter_135 {
            get {
                object obj = ResourceManager.GetObject("baga-inox-10-ly-mau-titan-cho-exciter-135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baga_inox_10_ly_mau_titan_cho_exciter_1351 {
            get {
                object obj = ResourceManager.GetObject("baga-inox-10-ly-mau-titan-cho-exciter-1351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baga_tinh_dien_cho_vespa {
            get {
                object obj = ResourceManager.GetObject("baga-tinh-dien-cho-vespa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baga_tinh_dien_cho_vespa1 {
            get {
                object obj = ResourceManager.GetObject("baga-tinh-dien-cho-vespa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bao_tay_driven_sbk_chinh_hang {
            get {
                object obj = ResourceManager.GetObject("bao-tay-driven-sbk-chinh-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bao_tay_driven_sbk_chinh_hang1 {
            get {
                object obj = ResourceManager.GetObject("bao-tay-driven-sbk-chinh-hang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bao_tay_driven_supermoto {
            get {
                object obj = ResourceManager.GetObject("bao-tay-driven-supermoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bao_tay_driven_supermoto1 {
            get {
                object obj = ResourceManager.GetObject("bao-tay-driven-supermoto1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap binh_dau_inox_salaya {
            get {
                object obj = ResourceManager.GetObject("binh-dau-inox-salaya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap binh_dau_inox_salaya1 {
            get {
                object obj = ResourceManager.GetObject("binh-dau-inox-salaya1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_co_son_carboncho_ex135 {
            get {
                object obj = ResourceManager.GetObject("bo-co-son-carboncho-ex135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_co_son_carboncho_ex1351 {
            get {
                object obj = ResourceManager.GetObject("bo-co-son-carboncho-ex1351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_noi_bbs_cho_vario_ab {
            get {
                object obj = ResourceManager.GetObject("bo-noi-bbs-cho-vario-ab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_noi_bbs_cho_vario_ab1 {
            get {
                object obj = ResourceManager.GetObject("bo-noi-bbs-cho-vario-ab1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_thang_dia_rcb_sau_cho_honda_sh {
            get {
                object obj = ResourceManager.GetObject("bo-thang-dia-rcb-sau-cho-honda-sh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_thang_dia_rcb_sau_cho_honda_sh1 {
            get {
                object obj = ResourceManager.GetObject("bo-thang-dia-rcb-sau-cho-honda-sh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap can_so_2_chieu_cho_exciter_155 {
            get {
                object obj = ResourceManager.GetObject("can-so-2-chieu-cho-exciter-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap can_so_2_chieu_cho_exciter_1551 {
            get {
                object obj = ResourceManager.GetObject("can-so-2-chieu-cho-exciter-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_duong_bong_dan_ao_goracing_1459 {
            get {
                object obj = ResourceManager.GetObject("chai-duong-bong-dan-ao-goracing-1459", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_duong_bong_dan_ao_goracing_14591 {
            get {
                object obj = ResourceManager.GetObject("chai-duong-bong-dan-ao-goracing-14591", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_lam_sach_dan_nhua_nham_vo_xe_goracing {
            get {
                object obj = ResourceManager.GetObject("chai-xit-lam-sach-dan-nhua-nham-vo-xe-goracing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_lam_sach_dan_nhua_nham_vo_xe_goracing1 {
            get {
                object obj = ResourceManager.GetObject("chai-xit-lam-sach-dan-nhua-nham-vo-xe-goracing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_sen_goracing_848 {
            get {
                object obj = ResourceManager.GetObject("chai-xit-sen-goracing-848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_sen_goracing_8481 {
            get {
                object obj = ResourceManager.GetObject("chai-xit-sen-goracing-8481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_ve_sinh_sen_goracing_8572 {
            get {
                object obj = ResourceManager.GetObject("chai-xit-ve-sinh-sen-goracing-8572", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chai_xit_ve_sinh_sen_goracing_85721 {
            get {
                object obj = ResourceManager.GetObject("chai-xit-ve-sinh-sen-goracing-85721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap che_ket_nuoc_cnc_titan_cho_yamaha_exciter_155 {
            get {
                object obj = ResourceManager.GetObject("che-ket-nuoc-cnc-titan-cho-yamaha-exciter-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap che_ket_nuoc_cnc_titan_cho_yamaha_exciter_1551 {
            get {
                object obj = ResourceManager.GetObject("che-ket-nuoc-cnc-titan-cho-yamaha-exciter-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coga_domino {
            get {
                object obj = ResourceManager.GetObject("coga-domino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coga_domino1 {
            get {
                object obj = ResourceManager.GetObject("coga-domino1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cot_banh_truoc_inox_salaya_cho_honda_winner {
            get {
                object obj = ResourceManager.GetObject("cot-banh-truoc-inox-salaya-cho-honda-winner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cot_banh_truoc_inox_salaya_cho_honda_winner1 {
            get {
                object obj = ResourceManager.GetObject("cot-banh-truoc-inox-salaya-cho-honda-winner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuc_keu_tim_xe_honda {
            get {
                object obj = ResourceManager.GetObject("cuc-keu-tim-xe-honda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuc_keu_tim_xe_honda1 {
            get {
                object obj = ResourceManager.GetObject("cuc-keu-tim-xe-honda1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cum_ga_tang_domino_2_day_ga {
            get {
                object obj = ResourceManager.GetObject("cum-ga-tang-domino-2-day-ga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cum_ga_tang_domino_2_day_ga1 {
            get {
                object obj = ResourceManager.GetObject("cum-ga-tang-domino-2-day-ga1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dau_suc_dong_co_liqui_moly_engine_flush {
            get {
                object obj = ResourceManager.GetObject("dau-suc-dong-co-liqui-moly-engine-flush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dau_suc_dong_co_liqui_moly_engine_flush1 {
            get {
                object obj = ResourceManager.GetObject("dau-suc-dong-co-liqui-moly-engine-flush1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap day_ga_thai {
            get {
                object obj = ResourceManager.GetObject("day-ga-thai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap day_ga_thai1 {
            get {
                object obj = ResourceManager.GetObject("day-ga-thai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_kingspeed {
            get {
                object obj = ResourceManager.GetObject("dia-kingspeed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_kingspeed1 {
            get {
                object obj = ResourceManager.GetObject("dia-kingspeed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_recto_42t_chinh_hang_cho_honda_sonic {
            get {
                object obj = ResourceManager.GetObject("dia-recto-42t-chinh-hang-cho-honda-sonic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_recto_42t_chinh_hang_cho_honda_sonic1 {
            get {
                object obj = ResourceManager.GetObject("dia-recto-42t-chinh-hang-cho-honda-sonic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_recto_46t_chinh_hang_cho_exciter_155 {
            get {
                object obj = ResourceManager.GetObject("dia-recto-46t-chinh-hang-cho-exciter-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dia_recto_46t_chinh_hang_cho_exciter_1551 {
            get {
                object obj = ResourceManager.GetObject("dia-recto-46t-chinh-hang-cho-exciter-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gang_tay_bao_ho_dai_ngon_mechanix {
            get {
                object obj = ResourceManager.GetObject("gang-tay-bao-ho-dai-ngon-mechanix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gang_tay_bao_ho_dai_ngon_mechanix1 {
            get {
                object obj = ResourceManager.GetObject("gang-tay-bao-ho-dai-ngon-mechanix1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gang_tay_chong_nang_xo_ngon_han_quoc {
            get {
                object obj = ResourceManager.GetObject("gang-tay-chong-nang-xo-ngon-han-quoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gang_tay_chong_nang_xo_ngon_han_quoc1 {
            get {
                object obj = ResourceManager.GetObject("gang-tay-chong-nang-xo-ngon-han-quoc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giap_inox_bao_ho_pro_biker_chinh_hang {
            get {
                object obj = ResourceManager.GetObject("giap-inox-bao-ho-pro-biker-chinh-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giap_inox_bao_ho_pro_biker_chinh_hang1 {
            get {
                object obj = ResourceManager.GetObject("giap-inox-bao-ho-pro-biker-chinh-hang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gu_inox_salaya_3_canh {
            get {
                object obj = ResourceManager.GetObject("gu-inox-salaya-3-canh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gu_inox_salaya_3_canh1 {
            get {
                object obj = ResourceManager.GetObject("gu-inox-salaya-3-canh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gulf_western_oil_syn_m_4t_premium_scooter_10w40_08l {
            get {
                object obj = ResourceManager.GetObject("gulf-western-oil-syn-m-4t-premium-scooter-10w40-08l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gulf_western_oil_syn_m_4t_premium_scooter_10w40_08l1 {
            get {
                object obj = ResourceManager.GetObject("gulf-western-oil-syn-m-4t-premium-scooter-10w40-08l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_print_printer_15001 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_print_printer_15001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_chan_gio_zhipat_v2 {
            get {
                object obj = ResourceManager.GetObject("kinh-chan-gio-zhipat-v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_chan_gio_zhipat_v21 {
            get {
                object obj = ResourceManager.GetObject("kinh-chan-gio-zhipat-v21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_gu_motogadget_tron {
            get {
                object obj = ResourceManager.GetObject("kinh-gu-motogadget-tron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_gu_motogadget_tron1 {
            get {
                object obj = ResourceManager.GetObject("kinh-gu-motogadget-tron1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_h2c_tron_1482 {
            get {
                object obj = ResourceManager.GetObject("kinh-h2c-tron-1482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_h2c_tron_14821 {
            get {
                object obj = ResourceManager.GetObject("kinh-h2c-tron-14821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_titan_kieu_dang_suzuki {
            get {
                object obj = ResourceManager.GetObject("kinh-titan-kieu-dang-suzuki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kinh_titan_kieu_dang_suzuki1 {
            get {
                object obj = ResourceManager.GetObject("kinh-titan-kieu-dang-suzuki1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_luoi_thep_do_danh_cho_honda {
            get {
                object obj = ResourceManager.GetObject("loc-gio-luoi-thep-do-danh-cho-honda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_luoi_thep_do_danh_cho_honda1 {
            get {
                object obj = ResourceManager.GetObject("loc-gio-luoi-thep-do-danh-cho-honda1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_tru_dna_hong {
            get {
                object obj = ResourceManager.GetObject("loc-gio-tru-dna-hong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_tru_dna_hong_54_chinh_hang {
            get {
                object obj = ResourceManager.GetObject("loc-gio-tru-dna-hong-54-chinh-hang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_tru_dna_hong_54_chinh_hang1 {
            get {
                object obj = ResourceManager.GetObject("loc-gio-tru-dna-hong-54-chinh-hang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loc_gio_tru_dna_hong1 {
            get {
                object obj = ResourceManager.GetObject("loc-gio-tru-dna-hong1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_n {
            get {
                object obj = ResourceManager.GetObject("logo_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Male {
            get {
                object obj = ResourceManager.GetObject("Male", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mam_rcb_8_cay_chinh_hang_cho_exciter_150_155 {
            get {
                object obj = ResourceManager.GetObject("mam-rcb-8-cay-chinh-hang-cho-exciter-150-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mam_rcb_8_cay_chinh_hang_cho_exciter_150_1551 {
            get {
                object obj = ResourceManager.GetObject("mam-rcb-8-cay-chinh-hang-cho-exciter-150-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motul_300v_factory_line_10w40_1l {
            get {
                object obj = ResourceManager.GetObject("motul-300v-factory-line-10w40-1l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motul_300v_factory_line_10w40_1l1 {
            get {
                object obj = ResourceManager.GetObject("motul-300v-factory-line-10w40-1l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motul_scooter_gear_plus_38 {
            get {
                object obj = ResourceManager.GetObject("motul-scooter-gear-plus-38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motul_scooter_gear_plus_381 {
            get {
                object obj = ResourceManager.GetObject("motul-scooter-gear-plus-381", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhong_mat_troi_15t_cho_honda_winner_sonic {
            get {
                object obj = ResourceManager.GetObject("nhong-mat-troi-15t-cho-honda-winner-sonic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhong_mat_troi_15t_cho_honda_winner_sonic1 {
            get {
                object obj = ResourceManager.GetObject("nhong-mat-troi-15t-cho-honda-winner-sonic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_gulf_western_oil_syn_m_4t_ester_pao_10w40 {
            get {
                object obj = ResourceManager.GetObject("nhot-gulf-western-oil-syn-m-4t-ester-pao-10w40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_gulf_western_oil_syn_m_4t_ester_pao_10w401 {
            get {
                object obj = ResourceManager.GetObject("nhot-gulf-western-oil-syn-m-4t-ester-pao-10w401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_gulf_western_oil_syn_m_4t_premium_10w40_1l {
            get {
                object obj = ResourceManager.GetObject("nhot-gulf-western-oil-syn-m-4t-premium-10w40-1l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_gulf_western_oil_syn_m_4t_premium_10w40_1l1 {
            get {
                object obj = ResourceManager.GetObject("nhot-gulf-western-oil-syn-m-4t-premium-10w40-1l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_hop_so_liqui_moly_racing_scooter_gear_oil {
            get {
                object obj = ResourceManager.GetObject("nhot-hop-so-liqui-moly-racing-scooter-gear-oil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_hop_so_liqui_moly_racing_scooter_gear_oil1 {
            get {
                object obj = ResourceManager.GetObject("nhot-hop-so-liqui-moly-racing-scooter-gear-oil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_liqui_moly_scooter_race_10w40_100ml {
            get {
                object obj = ResourceManager.GetObject("nhot-liqui-moly-scooter-race-10w40-100ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_liqui_moly_scooter_race_10w40_100ml1 {
            get {
                object obj = ResourceManager.GetObject("nhot-liqui-moly-scooter-race-10w40-100ml1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_maxima_full_syn_10w40 {
            get {
                object obj = ResourceManager.GetObject("nhot-maxima-full-syn-10w40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_maxima_full_syn_10w401 {
            get {
                object obj = ResourceManager.GetObject("nhot-maxima-full-syn-10w401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_motul_scoote_le_10w40_08l {
            get {
                object obj = ResourceManager.GetObject("nhot-motul-scoote-le-10w40-08l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_motul_scoote_le_10w40_08l1 {
            get {
                object obj = ResourceManager.GetObject("nhot-motul-scoote-le-10w40-08l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_repsol_mxr_platium_10w40_1l {
            get {
                object obj = ResourceManager.GetObject("nhot-repsol-mxr-platium-10w40-1l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_repsol_mxr_platium_10w40_1l1 {
            get {
                object obj = ResourceManager.GetObject("nhot-repsol-mxr-platium-10w40-1l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_wolver_racing_synthetic_10w40_492 {
            get {
                object obj = ResourceManager.GetObject("nhot-wolver-racing-synthetic-10w40-492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhot_wolver_racing_synthetic_10w40_4921 {
            get {
                object obj = ResourceManager.GetObject("nhot-wolver-racing-synthetic-10w40-4921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap non_bao_hiem_exciter {
            get {
                object obj = ResourceManager.GetObject("non-bao-hiem-exciter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap non_bao_hiem_exciter1 {
            get {
                object obj = ResourceManager.GetObject("non-bao-hiem-exciter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_lam_mat_goracing_1201 {
            get {
                object obj = ResourceManager.GetObject("nuoc-lam-mat-goracing-1201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_lam_mat_goracing_12011 {
            get {
                object obj = ResourceManager.GetObject("nuoc-lam-mat-goracing-12011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_lam_mat_liqui_moly_loai_khong_pha_804 {
            get {
                object obj = ResourceManager.GetObject("nuoc-lam-mat-liqui-moly-loai-khong-pha-804", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_lam_mat_liqui_moly_loai_khong_pha_8041 {
            get {
                object obj = ResourceManager.GetObject("nuoc-lam-mat-liqui-moly-loai-khong-pha-8041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmayexciter150 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmayexciter150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmayexciter1501 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmayexciter1501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaysatria2 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaysatria2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaysatria21 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaysatria21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaysirius {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaysirius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaysirius1 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaysirius1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaywave {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaywave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaywave1 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaywave1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaywinnerx {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaywinnerx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octitanlocmaywinnerx1 {
            get {
                object obj = ResourceManager.GetObject("octitanlocmaywinnerx1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ong_tieu_inox_honda_winner_x {
            get {
                object obj = ResourceManager.GetObject("ong-tieu-inox-honda-winner-x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ong_tieu_inox_honda_winner_x1 {
            get {
                object obj = ResourceManager.GetObject("ong-tieu-inox-honda-winner-x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap op_mat_na_carbon_limited_cho_exciter_155 {
            get {
                object obj = ResourceManager.GetObject("op-mat-na-carbon-limited-cho-exciter-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap op_mat_na_carbon_limited_cho_exciter_1551 {
            get {
                object obj = ResourceManager.GetObject("op-mat-na-carbon-limited-cho-exciter-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap op_po_inox_300i_zhipat_cho_shvn {
            get {
                object obj = ResourceManager.GetObject("op-po-inox-300i-zhipat-cho-shvn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap op_po_inox_300i_zhipat_cho_shvn1 {
            get {
                object obj = ResourceManager.GetObject("op-po-inox-300i-zhipat-cho-shvn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phu_gia_pha_nhot_liqui_moly_mo_s2 {
            get {
                object obj = ResourceManager.GetObject("phu-gia-pha-nhot-liqui-moly-mo-s2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phu_gia_pha_nhot_liqui_moly_mo_s21 {
            get {
                object obj = ResourceManager.GetObject("phu-gia-pha-nhot-liqui-moly-mo-s21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phu_gia_tang_toc_liqui_moly_speed_additive {
            get {
                object obj = ResourceManager.GetObject("phu-gia-tang-toc-liqui-moly-speed-additive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phu_gia_tang_toc_liqui_moly_speed_additive1 {
            get {
                object obj = ResourceManager.GetObject("phu-gia-tang-toc-liqui-moly-speed-additive1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phuoc_nitron_chinh_hang_viet_nam_cho_raider_satria {
            get {
                object obj = ResourceManager.GetObject("phuoc-nitron-chinh-hang-viet-nam-cho-raider-satria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phuoc_nitron_chinh_hang_viet_nam_cho_raider_satria1 {
            get {
                object obj = ResourceManager.GetObject("phuoc-nitron-chinh-hang-viet-nam-cho-raider-satria1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phuoc_yss_z_sport_chinh_hang_cho_honda_vario {
            get {
                object obj = ResourceManager.GetObject("phuoc-yss-z-sport-chinh-hang-cho-honda-vario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phuoc_yss_z_sport_chinh_hang_cho_honda_vario1 {
            get {
                object obj = ResourceManager.GetObject("phuoc-yss-z-sport-chinh-hang-cho-honda-vario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap po_4road_2009_hang_chuan_full_co_pat_cho_shvn_2020 {
            get {
                object obj = ResourceManager.GetObject("po-4road-2009-hang-chuan-full-co-pat-cho-shvn-2020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap po_4road_2009_hang_chuan_full_co_pat_cho_shvn_20201 {
            get {
                object obj = ResourceManager.GetObject("po-4road-2009-hang-chuan-full-co-pat-cho-shvn-20201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ro_giua_cho_exciter_155 {
            get {
                object obj = ResourceManager.GetObject("ro-giua-cho-exciter-155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ro_giua_cho_exciter_1551 {
            get {
                object obj = ResourceManager.GetObject("ro-giua-cho-exciter-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sen_phot_rk_428_elo {
            get {
                object obj = ResourceManager.GetObject("sen-phot-rk-428-elo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sen_phot_rk_428_elo1 {
            get {
                object obj = ResourceManager.GetObject("sen-phot-rk-428-elo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sen_rk_vang_den_428hsb {
            get {
                object obj = ResourceManager.GetObject("sen-rk-vang-den-428hsb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sen_rk_vang_den_428hsb1 {
            get {
                object obj = ResourceManager.GetObject("sen-rk-vang-den-428hsb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tham_cao_su_honda_vision {
            get {
                object obj = ResourceManager.GetObject("tham-cao-su-honda-vision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tham_cao_su_honda_vision1 {
            get {
                object obj = ResourceManager.GetObject("tham-cao-su-honda-vision1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap van_voi_inox_salaya {
            get {
                object obj = ResourceManager.GetObject("van-voi-inox-salaya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap van_voi_inox_salaya1 {
            get {
                object obj = ResourceManager.GetObject("van-voi-inox-salaya1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_metzeler {
            get {
                object obj = ResourceManager.GetObject("vo-metzeler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_metzeler1 {
            get {
                object obj = ResourceManager.GetObject("vo-metzeler1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_michelin_city_grip_2 {
            get {
                object obj = ResourceManager.GetObject("vo-michelin-city-grip-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_michelin_city_grip_2_10080 {
            get {
                object obj = ResourceManager.GetObject("vo-michelin-city-grip-2-10080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_michelin_city_grip_2_100801 {
            get {
                object obj = ResourceManager.GetObject("vo-michelin-city-grip-2-100801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_michelin_city_grip_21 {
            get {
                object obj = ResourceManager.GetObject("vo-michelin-city-grip-21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_aspira_sportivo {
            get {
                object obj = ResourceManager.GetObject("vo-xe-aspira-sportivo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_aspira_sportivo1 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-aspira-sportivo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_aspira_sportivo11 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-aspira-sportivo11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_aspira_sportivo2 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-aspira-sportivo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_563 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_5631 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-5631", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_pilot {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-pilot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_pilot1 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-pilot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_pilot11 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-pilot11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_camel_pilot2 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-camel-pilot2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_goodride {
            get {
                object obj = ResourceManager.GetObject("vo-xe-goodride", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_goodride_h993 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-goodride-h993", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_goodride_h9931 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-goodride-h9931", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vo_xe_goodride1 {
            get {
                object obj = ResourceManager.GetObject("vo-xe-goodride1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xinhan_spirit_beast_l27 {
            get {
                object obj = ResourceManager.GetObject("xinhan-spirit-beast-l27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xinhan_spirit_beast_l271 {
            get {
                object obj = ResourceManager.GetObject("xinhan-spirit-beast-l271", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
