//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanCNPM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_PHUTUNG;Integrated Secu" +
            "rity=True")]
        public string QL_PHUTUNGConnectionString {
            get {
                return ((string)(this["QL_PHUTUNGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_PHUTUNG1;Integrated Sec" +
            "urity=True")]
        public string QL_PHUTUNG1ConnectionString {
            get {
                return ((string)(this["QL_PHUTUNG1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_PHUTUNG4;Integrated Sec" +
            "urity=True")]
        public string QL_PHUTUNG4ConnectionString {
            get {
                return ((string)(this["QL_PHUTUNG4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_PHUTUNG4;Persist Securi" +
            "ty Info=True;User ID=sa;Password=sa2012")]
        public string QL_PHUTUNG4ConnectionString1 {
            get {
                return ((string)(this["QL_PHUTUNG4ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_PHUTUNG;Integrated Secu" +
            "rity=True")]
        public string QL_PHUTUNGConnectionString1 {
            get {
                return ((string)(this["QL_PHUTUNGConnectionString1"]));
            }
        }
    }
}
